services:
  sko_app:
    build:
      context: ./docker/php
    container_name: sko_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - laravel_sko
    depends_on:
      - sko_postgres

  sko_nginx:
    image: nginx:latest
    container_name: sko_nginx
    ports:
      - "8003:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_sko
    depends_on:
      - sko_app

  sko_postgres:
    image: postgres:15
    container_name: sko_db
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: Laravelpgslq++!
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel_sko

networks:
  laravel_sko:
    driver: bridge

volumes:
  pgdata:
